/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Collection: typeof import('./src/components/Collection.vue')['default']
    EquippedItems: typeof import('./src/components/EquippedItems.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Generators: typeof import('./src/components/Generators.vue')['default']
    PackDetailsModal: typeof import('./src/components/PackDetailsModal.vue')['default']
    PackOpeningModal: typeof import('./src/components/PackOpeningModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveLoadMenu: typeof import('./src/components/SaveLoadMenu.vue')['default']
    SynergyInfo: typeof import('./src/components/SynergyInfo.vue')['default']
    TypeChip: typeof import('./src/components/TypeChip.vue')['default']
    Upgrades: typeof import('./src/components/Upgrades.vue')['default']
  }
}
