/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EquippedItems: typeof import('./src/components/EquippedItems.vue')['default']
    Generators: typeof import('./src/components/Generators.vue')['default']
    PackOpeningModal: typeof import('./src/components/PackOpeningModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upgrades: typeof import('./src/components/Upgrades.vue')['default']
  }
}
